### ISSUE TITLE
BaseController: Pasar más de un nombre solo cuando sea necesario

### ISSUE THREAD

**Issue by RomeoCirel** [MatiasOlivera/ypf-tienda#35]
https://github.com/MatiasOlivera/ypf-tienda/blob/915884793a01d7cb1677ce523b938957a3d85bd2/server/app/Http/Controllers/BaseController.php#L58

Nunca Cambiamos esto 

-  **$nombre** deberia ser **Array** solo en el **UPDATE** que es el unico caso donde puede cambiar el valor de nombre.

- En los otros casos como **STORE**, **DELETE**, **INDEX**, **RESTORE** los valores no cambian  por lo que **$nombre** deberia ser **String**.

**Comment by MatiasOlivera** [comment]
No se puede usar la misma cadena en ambos mensajes, porque los mensajes de error resultantes no tendrían sentido o estarían mal escritos.

| Modelo            | Nombre              | Mensaje éxito                        | Mensaje error                                                     |
| ----------------- | ------------------- | ------------------------------------ | ----------------------------------------------------------------- |
| Cliente           | Juan                | **Juan** se ha creado                | Hubo un error al intentar guardar **al cliente Juan**             |
| Cliente domicilio | San Martin 100      | **San Martin 100** se ha creado      | Hubo un error al intentar guardar **el domicilio San Martin 100** |
| Cliente teléfono  | El teléfono de Juan | **El teléfono de Juan** se ha creado | Hubo un error al intentar guardar **el teléfono de Juan**         |
| Cliente email     | juan@gmail.com      | **juan@gmail.com** se ha creado      | Hubo un error al intentar guardar **el email juan@gmail.com**     |
| Cliente razón     | Evil Corp           | **Evil Corp** se ha creado           | Hubo un error al intentar guardar **a Evil Corp**                 |

Una solución es cambiar la frase con la que comienzan todos los mensajes de error por otra que permita generar un mensaje bien escrito usando unicamente el nombre.

**Comment by RomeoCirel** [comment]
El ejemplo correcto es el que declaraste en ClienteTelefono, asi le paso yo. 
Lo que se puede hacer es que la clase mensaje pase a mayúscula o minúscula la primer letra  dependiendo si es éxito o error. por ejemplo:

- ÉXITO:  **El domicilio San Martín 100** se ha creado.

- ERROR: Hubo un error al intentar guardar **el domicilio San Martín 100**

yo lo uso así por fuera del base controller:

https://github.com/MatiasOlivera/ypf-tienda/blob/915884793a01d7cb1677ce523b938957a3d85bd2/server/app/Http/Controllers/ClienteTelefonoController.php#L26

https://github.com/MatiasOlivera/ypf-tienda/blob/915884793a01d7cb1677ce523b938957a3d85bd2/server/app/Http/Controllers/ClienteTelefonoController.php#L68

https://github.com/MatiasOlivera/ypf-tienda/blob/915884793a01d7cb1677ce523b938957a3d85bd2/server/app/Http/Controllers/ClienteTelefonoController.php#L73

**Comment by MatiasOlivera** [comment]
Sí, eso esta bien para no repetir esa lógica en cada controlador

**Comment by MatiasOlivera** [comment]
El problema es que esa frase no se puede utilizar en todos los casos, hay algunas excepciones como el modelo cliente:

✔ **El cliente Juan** se ha creado
❌ Hubo un error al intentar guardar **el cliente Juan** ( Acá debería ser al cliente)

Lo que podríamos hacer es utilizar los métodos en los casos en donde la frase resultante quede bien escrita, y el constructor en el caso de las excepciones, en donde se necesite un mensaje más personalizado
