### ISSUE TITLE
No se puede crear una razón social

### ISSUE THREAD

**Issue by MatiasOlivera** [MatiasOlivera/ypf-tienda#41]
Cuando intento crear una razón social usando la ruta `api/clientes/{cliente}/razones` me aparece el siguiente error:

```
"SQLSTATE[HY000]: General error: 1364 Field 'fecha_carga' doesn't have a default value
SQL: insert into `razones_sociales` (`nombre`, `cuit`, `id_loc`, `updated_at`, `created_at`
values (dell, 12-34534534-3, 1, 2019-06-13 20:43:25, 2019-06-13 20:43:25))"
```

**Comment by RomeoCirel** [comment]
Eso estaba en un Triggers,

**Comment by MatiasOlivera** [comment]
Hay que agregar ese trigger en una migración, sino el test que pruebe si se puede crear una razón va a fallar

**Comment by MatiasOlivera** [comment]
¿Cuál era el nombre del trigger? Lo puedo agregar cuando haga los tests de razón social
