### ISSUE TITLE
Inconsistencia en las rutas de localidad

### ISSUE THREAD

**Issue by MatiasOlivera** [MatiasOlivera/ypf-tienda#54]
Las rutas del CRUD de localidad deberían empezar con `api/localidades` en vez de `api/provincias/localidades`. Son las únicas rutas que están diferentes que el resto.

Cuando se crea una localidad, se debería pasar el id de provincia en el cuerpo en vez de la ruta, de esa forma si el id no existe se puede devolver un error de validación. Actualmente si se pasa un id que no existe devuelve un código de estado 404 , lo que no es tan útil del lado del cliente.

https://github.com/MatiasOlivera/ypf-tienda/blob/3d7b033b4a991ae413e6584789a9337eed118b99/server/routes/api.php#L157-L169

**Comment by RomeoCirel** [comment]
Podría ser, pero como eso lo manejamos por debajo, y genera de forma automática la clase al mandarlo en la ruta, nose, de última podríamos validar del lado del cliente, así no rompemos la idea parcial del REST

**Comment by RomeoCirel** [comment]
Lo del nombre provincia/localidad si, quedo mal

**Comment by MatiasOlivera** [comment]
Tiene que haber una validación del lado del servidor, y debería devolver errores que sean fáciles de usar en el cliente y que indiquen claramente cuál es el problema. Actualmente se devuelve un código de estado 404 si no existe la localidad o la provincia.

El formulario de guardar debería enviar la siguiente estructura al servidor:

```json
{
    "nombre": "Mercedes",
    "provincia_id": 1
}
```

**Comment by MatiasOlivera** [comment]
> así no rompemos la idea parcial del REST

No me queda claro a que te referís
